### ISSUE TITLE
Reload command

### ISSUE THREAD

**Issue by dG9hc3Q** [moom0o/WorldStatsRewritten#3]
Reload command with permission so you can change your config _on the fly_

**Comment by moom0o** [comment]
What's the need for this

**Comment by AlexProgrammerDE** [comment]
Updating config > not having to use plugman

**Comment by moom0o** [comment]
The reload command already exists - /aef reload

**Comment by AlexProgrammerDE** [comment]
This is worldstats; not aef...

**Comment by moom0o** [comment]
Oh shit, I was looking at the webhook in discord

**Comment by moom0o** [comment]
Still who changes their stats command all the time

**Comment by moom0o** [comment]
I'll prob add it when I get home

**Comment by moom0o** [comment]
https://github.com/moom0o/WorldStatsRewritten/commit/6caab04c78a6d5267b84f90d833c06afbd356ca1
https://github.com/moom0o/WorldStatsRewritten/releases/tag/v1.6

**Comment by b00p1** [comment]
> Still who changes their stats command all the time

Plugman breaks sometimes.
